### ISSUE TITLE
Max 2 Config Migration to BPL 2.0.0

### ISSUE THREAD

**Issue by BuzzingBack** [runtime-shady-backroom/buttplug-lite#14]
Just a quick question, I notived in the patch notes for version that 

> migrated, except for the Lovense Max, which you will need to reconfigure. Your old config will be backed up to backup_config_v2.toml, in the config directory.

How would one go about prepping or migrating the tags over? Ive tried just copy and pasting my Config settings from version 1.0.0 to the new config and the cmd line keeps giving me a prompt for 

> buttplug_server: Attempting to load config from "C:\\Users\\[Redacted]\\AppData\\Roaming\\runtime-shady-backroom\\buttplug-lite\\config\\config.toml"
falling back to default config due to error: Error { inner: ErrorInner { kind: Custom, line: Some(5), col: 15, at: Some(77), message: "invalid type: string \"Vibration\", expected internally tagged enum MotorTypeV3", key: ["tags", "1", "feature_type"] } }

Hopefully im just over looking one little thing in the config.

**Comment by BuzzingBack** [comment]
For reference here is the current config file. 

>version = 3
port = 3031

[tags.1]
device_name = "Lovense Max"
feature_type = "Vibration"
feature_index = 0

[tags.2]
device_name = "Lovense Max"
feature_type = "Contraction"
feature_index = 0

**Comment by runtime-shady-backroom** [comment]
Honestly I'd just run buttplug-lite 2.0.0 then reference `backup_config_v2.toml` to remember what your existing tag names were, then reconfigure the Max using the GUI. If you really want to do it via editing the toml files alone I suppose that's possible, but the config format changed from v2 to v3.

The v2 config:
```toml
version = 2
port = 3031

[tags.c]
device_name = "Lovense Max"
feature_type = "Contraction"
feature_index = 0

[tags.m]
device_name = "Lovense Max"
feature_type = "Vibration"
feature_index = 0
```

The v3 config:
```toml
version = 3
port = 3031

[tags.c]
device_name = "Lovense Max"
feature_index = 1

[tags.c.feature_type]
type = "Scalar"
actuator_type = "Constrict"

[tags.m]
device_name = "Lovense Max"
feature_index = 0

[tags.m.feature_type]
type = "Scalar"
actuator_type = "Vibrate"
```
